version: "3.7"
services:
  springbootapp:
    image: panca/hotel-management-app:0.0.1
    network_mode: bridge
    container_name: hotel-management-app
    expose:
      - 9090
    ports:
      - 4000:9090
    environment:
       - DB_HOSTNAME=postgresdb
       - DB_PORT=5432
       - DB_DATABASE=hotelmanagement
       - DB_USERNAME=app_user
       - DB_PASSWORD=app_password
       - REDIS_HOST=redis_cache
       - REDIS_PORT=6379
       - REDIS_PASSWORD=
    depends_on:
      - postgresdb
    links:
      - postgresdb
      - redis_cache
  postgresdb:
    image: postgres:latest
    network_mode: bridge
    container_name: postgresdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    expose:
    - 5444
    ports:
      - 5444:5432
    environment:
        - POSTGRES_PASSWORD=admin
        - POSTGRES_USER=postgres
        - POSTGRES_DB=hotelmanagement
  redis_cache:
    image: redis
    network_mode: bridge
    container_name: redis_cache
    expose:
       - 6379
    ports:
      - "6379:6379"
volumes:
  postgres-data: