version: "3.7"
services:
  springbootapp:
    image: hotel-management-app:0.0.1
    network_mode: bridge
    container_name: hotel-management-app
    expose:
      - 9090
    ports:
      - 4000:9090
    restart: unless-stopped
    environment:
       - DB_HOSTNAME=postgresdb
       - DB_PORT=5432
       - DB_DATABASE=hotelmanagement
       - DB_USERNAME=app_user
       - DB_PASSWORD=app_password
    depends_on:
      - postgresdb
    links:
      - postgresdb
  postgresdb:
    image: postgres:latest
    network_mode: bridge
    container_name: postgresdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    expose:
    - 5432
    ports:
      - 5432:5432
    environment:
        - POSTGRES_PASSWORD=admin
        - POSTGRES_USER=postgres
        - POSTGRES_DB=hotelmanagement
    restart: unless-stopped
  
volumes:
  postgres-data: